/* DADO UN ARRAY DE OBJETOS DE PELICULAS (TITULO, DIRECTOR, VISTA), 
MOSTRAR TODAS LAS PELICULAS INDICANDO CUAL HAS VISTO Y CUAL NO

EJEMPLOS
misPeliculas(peliculas);

DEVUELVE
Ya has visto "Spiderman1"
Te falta por ver: "El Conjuro"

MOSTRAR TODAS LAS QUE HE VISTO Y LAS QUE NO

*/