/* DADO DOS CADENAS DE TEXTO, CREAR UN ALGORITMO QUE COMPRUEBE SI SON ANAGRAMAS ENTRE SI

UNA CADENA ES UN ANAGRAMA DE OTRA SI USA LOS MISMOS CARACTERES EN LA MISMA CANTIDAD

NO TENER EN CUENTA ESPACIOS, SIMBOLOS RAROS, PUNTOS, ETC.

EJEMPLO
anagramas("Riesgo", "Sergio") DEVUELVE TRUE
anagramas("Fer", "Izazaga") DEVUELVE FALSE

*/